version: '3'

services:
  app:
    build:
      context: sample-app
      dockerfile: docker/Dockerfile
    restart: always
    environment:
      - PROFILE=docker
    links:
      - logstash

  elasticsearch:
    build:
      context: elk/elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx1g"
    volumes:
      - ./elk/es-data:/usr/share/elasticsearch/data

  logstash:
    build:
      context: elk/logstash
    volumes:
      - ./elk/logstash/config/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "5044:5044"
    links:
      - elasticsearch

  kibana:
    build:
      context: elk/kibana
    volumes:
      - ./elk/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    links:
      - elasticsearch
