apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  labels:
    app: logstash
spec:
  replicas: 1
  template:
    metadata:
      name: logstash
      labels:
        app: logstash
    spec:
      containers:
        - name: logstash
          image: logstash:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5044
          volumeMounts:
            - mountPath: /usr/share/logstash/pipeline/logstash.conf
              name: logstash-volume
      restartPolicy: Always
      volumes:
        - name: logstash-volume
          hostPath:
            path: "/Users/cbezmen/Documents/projects/elk/elk/logstash/config/logstash.conf"
  selector:
    matchLabels:
      app: logstash
---
apiVersion: v1
kind: Service
metadata:
  name: logstash
spec:
  selector:
    app: logstash
  type: LoadBalancer
  ports:
    - port: 5044
      targetPort: 5044
