apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
  labels:
    app: sample-app
spec:
  replicas: 1
  template:
    metadata:
      name: sample-app
      labels:
        app: sample-app
    spec:
      containers:
        - name: sample-app
          image: sample-app:v1
          env:
            - name: PROFILE
              value: docker
      restartPolicy: Always
  selector:
    matchLabels:
      app: sample-app
---
apiVersion: v1
kind: Service
metadata:
  name: sample-app
spec:
  selector:
    app: sample-app
  clusterIP: None
  ports:
    - name: headless
      port: 55555
      targetPort: 0
